### ISSUE TITLE
Add computeDryLayout

### ISSUE THREAD

**Issue by jamesblasco** [letsar/gap#5]
Hello! 
In Flutter 1.25, there is a new method in RenderObject called computeDryLayout. It is used to calculate the size of the RenderObject by given constraints without the need to layout it.

![image](https://user-images.githubusercontent.com/19904063/103704818-35c3ef80-4faa-11eb-83d8-b27be7ec460e.png)
https://flutter.dev/docs/release/breaking-changes/renderbox-dry-layout

As an example here is the implementation for RenderConstrainedBox used for SizedBox.

https://github.com/flutter/flutter/blob/4901744e62f67ad10440725d2c97e84e66ce77f5/packages/flutter/lib/src/rendering/proxy_box.dart#L288-L295

If you need, I would be happy to help with a PR

**Comment by letsar** [comment]
Hi @jamesblasco ! Thanks for raising this issue :-).
I have no bandwidth for the moment so I would be very happy if you could make this PR. The only thing I would need to do then, would be to create a new branch for this, because this change cannot be in the master branch where I want it to be available for the stable branch of Flutter.
I also wonder if we can have more than one pre-release in pub.dev, do you if it's possible?

**Comment by letsar** [comment]
I created the beta branch for this. It would be great if you can make this PR to this branch. Thanks again

**Comment by jamesblasco** [comment]
I will do that then! Thanks.  I think it is possible to publish multiple pre release versions with different names. But we can wait until it reaches beta and add it inside null safety

**Comment by letsar** [comment]
Added in 2.0
